name: 'training website Terraform'

on: [push, pull_request]
 
permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash

    steps:
    - name: setup the SSH key
      run: |  
        echo ${{ secrets.PRIVATE_KEY_NAME }} | base64 --decode > ~/.ssh/terraform && chmod 600 ~/.ssh/terraform

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::120666943157:role/github_workflow_terraform
        aws-region: us-east-1
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
    
    - uses: dorny/paths-filter@v2
      id: changes
      with: 
          filters: |
            src:
              - 'examples/terraform_aws_qxf2_training_website/**'
              - '.github/workflows/training_website'

    - name: Terraform Init
      if: steps.changes.outputs.src=='true'
      run: cd examples/terraform_aws_qxf2_training_website && terraform init

    - name: Terraform Validate
      run: cd examples/terraform_aws_qxf2_training_website && terraform validate -no-color

    - name: Terraform Plan
      run: cd examples/terraform_aws_qxf2_training_website && terraform plan -input=false

      # On push to "main", deploy the Terraform infrastructure
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: cd examples/terraform_aws_qxf2_training_website && terraform apply -auto-approve -input=false